update

diff --git a/.github/workflows/send_notes.yml b/.github/workflows/send_notes.yml
--- a/.github/workflows/send_notes.yml
+++ b/.github/workflows/send_notes.yml
@@ -16,7 +16,7 @@ jobs:
         with:
           format: space-delimited
           token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Printing
+      - name: List all changed markdown files
         run: |
           echo "All:"
           echo "${{ steps.abc.outputs.all }}"
@@ -30,3 +30,20 @@ jobs:
           echo "${{ steps.abc.outputs.modified }}"
           echo "Added+Modified:"
           echo "${{ steps.abc.outputs.added_modified }}"
+      - name: Send notes to server
+        if: steps.changed-markdown-files.outputs.any_changed == 'true'
+        env:
+          ALL_CHANGED_FILES: ${{ steps.abc.outputs.modified }}
+          SEND_NOTES_URL: ${{ secrets.SEND_NOTES_URL }}
+        run: |
+          for file in ${ALL_CHANGED_FILES}; do
+            content=$(cat "$file" | jq -sR .)
+            json_data="{\"file\":\"$file\",\"content\":$content}"
+            echo "JSON Data: $json_data"
+            response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" $SEND_NOTES_URL)
+            echo "Server response: $response"
+            if [ "$response" -ne 200 ]; then
+              echo "Failed to send notes to server for file $file. Response code: $response"
+              exit 1
+            fi
+          done
